### ISSUE TITLE
Cannot Compile on MacOS (v12.7.6)

### ISSUE THREAD

**Issue by BitcoinMechanic** [bitcoinknots/bitcoin#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Fails to compile at this point:

```
  CXX      libbitcoin_node_a-validationinterface.o
In file included from rest.cpp:10:
In file included from ./rest.h:8:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:522:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:653:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:500:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/function.h:18:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/allocator_traits.h:298:9: error: no matching function for call to 'construct_at'
        _VSTD::construct_at(__p, _VSTD::forward<_Args>(__args)...);
        ^~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:858:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_ABI_NAMESPACE
              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:948:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::string_view>>::construct<std::string_view, const char *&, const char *&, void, void>' requested here
    __alloc_traits::construct(this->__alloc(), _VSTD::__to_address(__tx.__pos_),
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:1706:9: note: in instantiation of function template specialization 'std::vector<std::string_view>::__construct_one_at_end<const char *&, const char *&>' requested here
        __construct_one_at_end(_VSTD::forward<_Args>(__args)...);
        ^
./util/spanparsing.h:55:17: note: in instantiation of function template specialization 'std::vector<std::string_view>::emplace_back<const char *&, const char *&>' requested here
            ret.emplace_back(start, it);
                ^
./util/spanparsing.h:74:12: note: in instantiation of function template specialization 'spanparsing::Split<std::string_view>' requested here
    return Split<T>(sp, std::string_view{&sep, 1});
           ^
rest.cpp:841:46: note: in instantiation of function template specialization 'spanparsing::Split<std::string_view>' requested here
            const auto txid_out{spanparsing::Split<std::string_view>(uriParts[i], '-')};
                                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/construct_at.h:35:16: note: candidate template ignored: substitution failure [with _Tp = std::string_view, _Args = <const char *&, const char *&>]: no matching constructor for initialization of 'std::string_view'
constexpr _Tp* construct_at(_Tp* __location, _Args&& ...__args) {
               ^
1 error generated.
make[2]: *** [libbitcoin_node_a-rest.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

### Expected behaviour

To successfully compile

### Steps to reproduce

.

### How did you obtain Bitcoin Knots

Other

### What version of Bitcoin Knots are you using?

v27.4.1

### Operating system and version

MacOS (v12.7.6)

**Comment by luke-jr** [comment]
Is this still an issue with 28.1?

**Comment by BitcoinMechanic** [comment]
No, it compiles fine now.
